/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladores.ControladorCitas;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author pc
 */
public class FrmAdministrarSecretaria extends javax.swing.JInternalFrame {
    FrmCitas frmCitas;
     FrmModificarUsuario frmModificarUsuario;
    ControladorCitas controladorCitas;
    FrmUsuario frmUsuario;
    FrmEliminarUsuario frmEliminarUsuario;
  

    /**
     * Creates new form FrmAdministrarUsuario
     */
    public FrmAdministrarSecretaria() {
        initComponents();
    }

    public void obtenerFrm(FrmUsuario frm) {
        this.frmUsuario = frm;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        btnCitas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mi Perfil");

        lblNombre.setText("Nombre");

        lblEliminar.setText("Eliminar Usuario");
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });

        lblContrasena.setText("Cambiar Contraseña");
        lblContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContrasenaMouseClicked(evt);
            }
        });

        lblCorreo.setText("Correo Electronico");

        lblCedula.setText("Cedula");

        lblTel.setText("Telefono");

        btnCitas.setText("Citas");
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTel)
                    .addComponent(lblCorreo)
                    .addComponent(lblCedula)
                    .addComponent(lblNombre))
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEliminar)
                        .addGap(24, 24, 24))
                    .addComponent(btnCitas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasena, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblContrasena))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEliminar)
                            .addComponent(lblCedula))
                        .addGap(32, 32, 32)
                        .addComponent(lblCorreo)
                        .addGap(28, 28, 28)
                        .addComponent(lblTel)
                        .addGap(18, 18, 18)
                        .addComponent(btnCitas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed

        this.frmCitas = new FrmCitas();
        frmCitas.obtenerFrm(frmUsuario);
        this.frmUsuario.getjDesktopPane1().add(frmCitas);
        frmCitas.show();
    }//GEN-LAST:event_btnCitasActionPerformed

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
      int clickCount = evt.getClickCount();
        lblEliminar.setForeground(Color.BLUE);
        if (clickCount == 2) {
            lblEliminar.setForeground(Color.BLACK);
            frmEliminarUsuario= new FrmEliminarUsuario();
            frmEliminarUsuario.obtenerfrm(this);
            frmUsuario.jDesktopPane1.add(frmEliminarUsuario);
            frmEliminarUsuario.show();
           
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContrasenaMouseClicked
                int clickCount = evt.getClickCount();
        lblContrasena.setForeground(Color.BLUE);
        if (clickCount == 2) {
            lblContrasena.setForeground(Color.BLACK);
            frmModificarUsuario= new FrmModificarUsuario();
            frmModificarUsuario.obtenerfrm(this);
            frmModificarUsuario.obtenerfrm(frmUsuario);
            frmUsuario.jDesktopPane1.add(frmModificarUsuario);
            frmModificarUsuario.show();
        }
           
    }//GEN-LAST:event_lblContrasenaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCitas;
    public static javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblCedula;
    public static javax.swing.JLabel lblContrasena;
    public static javax.swing.JLabel lblCorreo;
    public static javax.swing.JLabel lblEliminar;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblTel;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public JLabel getLblCorreo() {
        return lblCorreo;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JLabel getLblTel() {
        return lblTel;
    }

}
