package Vista;

import Controladores.ControladorRevisiones;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

public class FrmRevisiones extends javax.swing.JInternalFrame {
private FrmUsuario frmUsuario;
FrmInformacionVehiculo frmInformacionVehiculo;
ControladorRevisiones controladorRevisiones;
FrmVisualizadorCitas frmVisualizadorCitas;

 private String placa;
    private String fecha;
    private String hora;
    
    
    public void obtenerFrm(FrmUsuario frmUsuario) {
        this.frmUsuario=frmUsuario;
    }
  public void obtenerControladorRevisiones(ControladorRevisiones controladorRevisiones){
      this.controladorRevisiones=controladorRevisiones;
  }
  public void obtenerControladorRevisiones(FrmVisualizadorCitas frmVisualizadorCitas){
      this.frmVisualizadorCitas=frmVisualizadorCitas;
  }
  
  
  public void obtenerDatos(String placa, String fecha, String hora){
      this.placa=placa;
      this.fecha=fecha;
      this.hora=hora;
    
  }
    /**
     * Creates new form FrmReviciones
     */
    public FrmRevisiones() {
        initComponents();
        
          }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoInspeccion = new javax.swing.ButtonGroup();
        btngEstado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtnInspeccion = new javax.swing.JRadioButton();
        rbtnReinspeccion = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        rbtnAprobado = new javax.swing.JRadioButton();
        rbtnReprobado = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnInfoVehiculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Revisiones");

        jLabel1.setText("Fecha: ");

        lblFecha.setText(" ");

        jLabel2.setText("Hora: ");

        lblHora.setText(" ");

        jLabel3.setText("Técnico: ");

        lblTecnico.setText(" ");

        jLabel4.setText("Tipo de revisión: ");

        btngTipoInspeccion.add(rbtnInspeccion);
        rbtnInspeccion.setText("Inspección");

        btngTipoInspeccion.add(rbtnReinspeccion);
        rbtnReinspeccion.setText("Reinspección");

        jLabel5.setText("Observaciones de la revisión:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel6.setText("Estado:");

        btngEstado.add(rbtnAprobado);
        rbtnAprobado.setText("Aprobado");

        btngEstado.add(rbtnReprobado);
        rbtnReprobado.setText("Reprobado");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnInfoVehiculo.setText("Informacion del Vehiculo");
        btnInfoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoVehiculoActionPerformed(evt);
            }
        });

        jLabel7.setText("Placa:");

        lblPlaca.setText(" ");

        jButton1.setText("llenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnAprobado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnReprobado)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(btnInfoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnInspeccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnReinspeccion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 103, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblFecha)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTecnico)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtnInspeccion)
                    .addComponent(rbtnReinspeccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnAprobado)
                    .addComponent(rbtnReprobado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnInfoVehiculo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (btngEstado.isSelected(null) || btngTipoInspeccion.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "No puede dejar campos vacíos");
        }else{
          controladorRevisiones=new ControladorRevisiones(this);
            this.controladorRevisiones.insertarRevision();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnInfoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoVehiculoActionPerformed
        frmInformacionVehiculo=new FrmInformacionVehiculo();
          frmUsuario.getjDesktopPane1().add(frmInformacionVehiculo);
       frmInformacionVehiculo.obtenerfrmUsuario(frmUsuario);
         frmInformacionVehiculo.obtenerfrmUsuario(this);
        frmInformacionVehiculo.show();
    }//GEN-LAST:event_btnInfoVehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controladorRevisiones=new ControladorRevisiones(this,this.getFecha(),this.getHora(),this.getPlaca());
        this.controladorRevisiones.llenarInformacion();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInfoVehiculo;
    private javax.swing.ButtonGroup btngEstado;
    private javax.swing.ButtonGroup btngTipoInspeccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JRadioButton rbtnAprobado;
    private javax.swing.JRadioButton rbtnInspeccion;
    private javax.swing.JRadioButton rbtnReinspeccion;
    private javax.swing.JRadioButton rbtnReprobado;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public void setLblPlaca(JLabel lblPlaca) {
        this.lblPlaca = lblPlaca;
    }

    public void setLblTecnico(JLabel lblTecnico) {
        this.lblTecnico = lblTecnico;
    }

    public JLabel getLblTecnico() {
        return lblTecnico;
    }

    public JRadioButton getRbtnAprobado() {
        return rbtnAprobado;
    }

    public JRadioButton getRbtnInspeccion() {
        return rbtnInspeccion;
    }

    public JRadioButton getRbtnReinspeccion() {
        return rbtnReinspeccion;
    }

    public JRadioButton getRbtnReprobado() {
        return rbtnReprobado;
    }

    public JTextArea getTxtRevision() {
        return txtObservaciones;
    }

    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public FrmUsuario getFrmUsuario() {
        return frmUsuario;
    }

    public ButtonGroup getBtngEstado() {
        return btngEstado;
    }

    public ButtonGroup getBtngTipoInspeccion() {
        return btngTipoInspeccion;
    }

    public JTextArea getTxtObservaciones() {
        return txtObservaciones;
    }





}
