package Vista;

import Controladores.ControladorCrearUsuario;
import Controladores.ControladorSecretaria;
import Controladores.ControladorTecnico;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Controladores.ControladorUsuarios;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

public class FrmUsuario extends javax.swing.JFrame {
    
    

    ControladorUsuarios controladorUser;
    private boolean tipoUsuario;
     ControladorTecnico controladorTec;
     FrmAdministrarTecnico frmTecnico ;
     FrmAdministrarSecretaria frmSecre;
     FrmCrearUsuario frmCrear;
     ControladorCrearUsuario controladorCrearUsuario;
     ControladorSecretaria Secr;
     FrmCitas frmCitas;
   FrmVisualizadorCitas frmVCitas;
    public FrmCitas getFrmCitas() {
        return frmCitas;
    }

    public FrmVisualizadorCitas getFrmVCitas() {
        return frmVCitas;
    }
    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(FrmUsuario.MAXIMIZED_BOTH);
//       controladorUser.conectar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        lblCrearUsuario = new javax.swing.JLabel();
        lblCambiarContrasena = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblConexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Riteve");

        jDesktopPane1.setNextFocusableComponent(this);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Contraseña: ");

        lblCrearUsuario.setText("Crear Usuario");
        lblCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearUsuarioMouseClicked(evt);
            }
        });

        lblCambiarContrasena.setText("Cambiar Contraseña");
        lblCambiarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarContrasenaMouseClicked(evt);
            }
        });

        jLabel5.setText("  |");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(lblCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCambiarContrasena)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(lblConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearUsuario)
                    .addComponent(lblCambiarContrasena)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(lblConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32571, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCedula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblCrearUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblCambiarContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnIngresar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblConexion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearUsuarioMouseClicked
        int clickCount = evt.getClickCount();
        lblCrearUsuario.setForeground(Color.BLUE);
        if (clickCount == 2) {
            lblCrearUsuario.setForeground(Color.BLACK);
            frmCrear = new FrmCrearUsuario();
            frmCrear.obtenerfrm(this);
            jDesktopPane1.add(frmCrear);
            frmCrear.show();
            this.controladorCrearUsuario=new ControladorCrearUsuario(this);
        }
    }//GEN-LAST:event_lblCrearUsuarioMouseClicked

    private void lblCambiarContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContrasenaMouseClicked
        int clickCount = evt.getClickCount();
        lblCambiarContrasena.setForeground(Color.BLUE);
        if (clickCount == 2) {
            lblCambiarContrasena.setForeground(Color.BLACK);
            FrmModificarUsuario modif = new FrmModificarUsuario();
            jDesktopPane1.add(modif);
            modif.show();
        }
    }//GEN-LAST:event_lblCambiarContrasenaMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        controladorUser = new ControladorUsuarios(this);
        if (controladorUser.verficarUsuario().equals("TECNICO")) {
            this.setTipoUsuario(true);
            frmTecnico = new FrmAdministrarTecnico();
            frmTecnico.obtenerFrm(this);
            jDesktopPane1.add(frmTecnico);
            frmTecnico.show();
            controladorUser.tipoUsuario();
             this.controladorTec =new ControladorTecnico(this);
        } else {
            if (controladorUser.verficarUsuario().equals("SECRETARIA")) {
                this.setTipoUsuario(false);
               frmSecre = new FrmAdministrarSecretaria();
               frmSecre.obtenerFrm(this);
                jDesktopPane1.add(frmSecre);
                
                frmSecre.show();
                controladorUser.tipoUsuario();
                ControladorSecretaria Secr=new ControladorSecretaria(this);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrecta");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnIngresar;
    public javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lblCambiarContrasena;
    public static javax.swing.JLabel lblConexion;
    public static javax.swing.JLabel lblCrearUsuario;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblConexion() {
        return lblConexion;
    }

    public JPasswordField getTxtContrasena() {
        return txtContrasena;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public void setLblConexion(JLabel lblConexion) {
        this.lblConexion = lblConexion;
    }

    public boolean isTipoUsuario() {
        return tipoUsuario;
    }

    public void setTipoUsuario(boolean tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public FrmAdministrarTecnico getFrmTecnico() {
        return frmTecnico;
    }

    public FrmAdministrarSecretaria getFrmSecre() {
        return frmSecre;
    }

    public FrmCrearUsuario getCrear() {
        return frmCrear;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }
    
    

}
